# Generated by Django 5.0 on 2024-03-09 20:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('sender_name', models.CharField(max_length=50)),
                ('sender_address', models.CharField(max_length=50)),
                ('sender_email', models.EmailField(max_length=254)),
                ('reciever_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reciever_address', models.CharField(blank=True, max_length=50, null=True)),
                ('reciever_email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_time', models.DateField(blank=True, null=True)),
                ('arrival_time', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_number', models.CharField(default='EXWA50be1dcc-3e91-4e01-ORDER', max_length=30, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Processed'), (2, 'Dispatch'), (3, 'En Route '), (4, 'Delivered')], default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
