# Generated by Django 5.0 on 2024-03-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWAdaef2060-2028-4fb7-ORDER', max_length=30, unique=True),
        ),
    ]
