# Generated by Django 5.0 on 2024-03-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWAc034ed1a-c884-4343-ORDER', max_length=30, unique=True),
        ),
    ]
