# Generated by Django 5.0 on 2024-01-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_alter_order_tracking_number_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWAd70f5c81-3639-4742-ORDER', max_length=30, unique=True),
        ),
    ]
