# Generated by Django 5.0 on 2024-07-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_order_arrival_date_order_carrier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA79555a22-097d-45ef-ORDER', max_length=30, unique=True),
        ),
    ]
