# Generated by Django 5.0 on 2024-07-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0006_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sender_hone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Picked up'), (3, 'On hold'), (4, 'Out for delivery'), (5, 'In Transit'), (6, 'Enroute'), (7, 'Cancelled'), (8, 'Delivered'), (9, 'Returned'), (10, 'Intercepted by DEA'), (11, 'Held by Customs')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA92064d79-17f1-4727-ORDER', max_length=30, unique=True),
        ),
    ]
