# Generated by Django 5.0 on 2024-07-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0007_order_sender_hone_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sender_hone',
            new_name='sender_phone',
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWAe9d002e6-8821-45d8-ORDER', max_length=30, unique=True),
        ),
    ]
