# Generated by Django 5.0 on 2024-07-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0008_rename_sender_hone_order_sender_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA76476701-b76d-4650-ORDER', max_length=30, unique=True),
        ),
    ]
