# Generated by Django 5.0 on 2024-03-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
