# Generated by Django 5.0 on 2024-01-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWAb8475ede-4f59-44b8-ORDER', max_length=30, unique=True),
        ),
    ]
