# Generated by Django 5.0 on 2024-02-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA29234fb1-7c0c-4183-ORDER', max_length=30, unique=True),
        ),
    ]
