# Generated by Django 5.0 on 2024-01-30 20:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
